services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      VIRTUAL_HOST: 'app.kojima.localhost'
    volumes:
      - ./frontend:/app
    tty: true
    stdin_open: true
    networks:
      - kojima
      - my-network
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      VIRTUAL_HOST: 'api.kojima.localhost'
    volumes:
      - ./backend:/app
    tty: true
    stdin_open: true
    networks:
      - kojima
      - my-network

networks:
  kojima:
  my-network:
    external: true
